import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { scan } from '../skills/diagnose/scripts/labs.js';

/** Write a set of files into a fresh directory and scan it. */
function scanFiles(files, options = {}) {
  const root = mkdtempSync(join(tmpdir(), 'slopmd-test-'));
  for (const [rel, content] of Object.entries(files)) {
    const path = join(root, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  return scan({ path: options.file ? join(root, options.file) : root });
}

function rules(result, rule) {
  return result.findings.filter((f) => f.rule === rule);
}

const SECRET = 'const apiKey = "sk-abcdefghijklmnopqrstuvwxyz012345";'; // slopmd-ignore

// --- hardcoded-secret: interpolation placeholders (issue #1) ---

test('a value that is entirely a placeholder reference is not a secret', () => {
  const result = scanFiles({
    'config.yaml': [
      'password: "{{secret.sap_password}}"',
      'client_secret: "${GRAPH_CLIENT_SECRET}"',
      'auth_token: "$SLOPMD_TOKEN"',
      'access_key: "%(vault_access_key)s"',
    ].join('\n'),
  });
  assert.deepEqual(rules(result, 'hardcoded-secret'), []);
});

test('a real secret is still reported next to placeholders', () => {
  const result = scanFiles({
    'config.yaml': 'password: "{{secret.x}}"\ndb_password: "hunter2supersecret"\n',
  });
  assert.equal(rules(result, 'hardcoded-secret').length, 1);
  assert.equal(rules(result, 'hardcoded-secret')[0].line, 2);
});

// --- generated files (issue #5) ---

test('generated files are skipped, by name and by header marker', () => {
  const result = scanFiles({
    'routeTree.gen.ts': SECRET,
    'api.pb.go': SECRET,
    'schema_pb2.py': SECRET,
    'marked.ts': '// @generated by fooc\n' + SECRET,
    'header.go': '// Code generated by protoc-gen-go. DO NOT EDIT.\n' + SECRET,
  });
  assert.equal(result.stats.filesScanned, 0);
  assert.deepEqual(result.findings, []);
});

test('a hand-written file that merely mentions @generated is still scanned', () => {
  const result = scanFiles({
    'emit.ts': "const BANNER = '// @generated by gqlgen. DO NOT EDIT.';\n" + SECRET,
  });
  assert.equal(result.stats.filesScanned, 1);
  assert.equal(rules(result, 'hardcoded-secret').length, 1);
});

test('a changelog whose prose spans "code generated by" and "do not edit" is still scanned', () => {
  const result = scanFiles({
    'CHANGELOG.md': [
      'Code generated by v2 of the compiler is faster now.',
      'Note: do not edit released entries, append instead.',
      '',
      'This release is truly comprehensive and seamless.',
    ].join('\n'),
  });
  assert.equal(result.stats.filesScanned, 1);
  assert.ok(rules(result, 'marketing-prose').length > 0);
});

test('a hand-written legacy file with eslint-disable and ts-nocheck is still scanned', () => {
  const result = scanFiles({ 'legacy.ts': '/* eslint-disable */\n// @ts-nocheck\n' + SECRET });
  assert.equal(result.stats.filesScanned, 1);
  assert.equal(rules(result, 'hardcoded-secret').length, 1);
});

test('filenames that merely contain "gen" are not treated as generated', () => {
  const result = scanFiles({ 'oxygen.ts': SECRET, 'codegen.ts': SECRET, 'gen.ts': SECRET });
  assert.equal(result.stats.filesScanned, 3);
  assert.equal(rules(result, 'hardcoded-secret').length, 3);
});

// --- slopmd-ignore (issue #8) ---

test('a marker in the comment block above suppresses the whole statement', () => {
  const result = scanFiles({
    'root.tsx': [
      'export function Root() {',
      '  return (',
      '    <script',
      '      // El catch vacio es deliberado: la app sigue andando si falla.',
      '      // slopmd-ignore',
      '      dangerouslySetInnerHTML={{',
      '        __html:',
      "          \"navigator.serviceWorker.register('/sw.js').catch(function(){})\",", // slopmd-ignore
      '      }}',
      '    />',
      '  )',
      '}',
    ].join('\n'),
  });
  assert.deepEqual(rules(result, 'broad-catch'), []);
});

test('a marker does not reach into a callback body', () => {
  const result = scanFiles({
    'effect.js': [
      '// slopmd-ignore',
      'useEffect(() => {',
      '  console.log(1);',
      '  ' + SECRET,
      '});',
    ].join('\n'),
  });
  assert.equal(rules(result, 'hardcoded-secret').length, 1, 'a secret inside the callback must survive');
});

test('a marker does not reach into a function body', () => {
  const result = scanFiles({
    'block.ts': ['// slopmd-ignore', 'export function wrapper() {', '  ' + SECRET, '}'].join('\n'),
  });
  assert.equal(rules(result, 'hardcoded-secret').length, 1);
});

test('an unbalanced bracket inside a string does not leak the suppression', () => {
  const result = scanFiles({
    'leak.js': ['// slopmd-ignore', "const template = 'open brace: {';", SECRET].join('\n'),
  });
  assert.equal(rules(result, 'hardcoded-secret').length, 1, 'the secret is a separate statement');
});

test('a marker suppresses a multi-line return statement', () => {
  const result = scanFiles({
    'ret.js': [
      'export function load() {',
      '  // slopmd-ignore',
      "  return fetch('/api', {",
      '    timeout: 30000,',
      '  });',
      '}',
    ].join('\n'),
  });
  assert.deepEqual(rules(result, 'magic-number'), []);
});

test('a marker still suppresses a finding on the comment line below it', () => {
  const result = scanFiles({
    'todo.js': ['// slopmd-ignore', '// TODO: revisit', 'export const value = 1;'].join('\n'),
  });
  assert.deepEqual(rules(result, 'todo-no-ref'), []);
});

test('a marker on the flagged line still works', () => {
  const result = scanFiles({ 'same.ts': SECRET + ' // slopmd-ignore' });
  assert.deepEqual(rules(result, 'hardcoded-secret'), []);
});

// --- magic-number (issue #7) ---

test('HTTP status codes are allowed next to a status, and only there', () => {
  const result = scanFiles({
    'gateway.ts': [
      'export function classify(err, delay) {',
      "  if (err.status === 401 || err.status === 403) return 'auth'",
      "  if (err.status === 404) return 'missing'",
      '  setTimeout(retry, 500)',
      '  return delay * 86400000',
      '}',
    ].join('\n'),
  });
  const found = rules(result, 'magic-number').map((f) => f.line);
  assert.deepEqual(found, [4, 5], 'setTimeout(fn, 500) and 86400000 are magic; status codes are not');
});

test('.slopmd.json extends the allowlist and is found from a nested target', () => {
  const files = {
    '.slopmd.json': '{"magic-number": {"ignore": [7350]}}',
    'src/pricing.ts': 'export function total(n) {\n  return n * 7350 + 86400000\n}',
  };
  const whole = scanFiles(files);
  assert.deepEqual(rules(whole, 'magic-number').map((f) => f.message.match(/\d+/)[0]), ['86400000']);

  const single = scanFiles(files, { file: 'src/pricing.ts' });
  assert.deepEqual(
    rules(single, 'magic-number').map((f) => f.message.match(/\d+/)[0]),
    ['86400000'],
    'the config at the root must apply when scanning one nested file',
  );
});

test('a mistyped config key is an error, not a silent default', () => {
  assert.throws(
    () => scanFiles({ '.slopmd.json': '{"magicNumber": {"ignore": [7350]}}', 'a.ts': 'const x = 1' }),
    /unknown key "magicNumber"/,
  );
  assert.throws(
    () => scanFiles({ '.slopmd.json': '{"magic-number": {"ignored": [7350]}}', 'a.ts': 'const x = 1' }),
    /unknown key "magic-number.ignored"/,
  );
  assert.throws(
    () => scanFiles({ '.slopmd.json': '{"magic-number": {"ignore": [-1]}}', 'a.ts': 'const x = 1' }),
    /non-negative integers/,
  );
  assert.throws(
    () => scanFiles({ '.slopmd.json': '{ nope', 'a.ts': 'const x = 1' }),
    /not valid JSON/,
  );
});

// --- deep-nesting (issue #6) ---

const NESTED_JS = [
  'export function messy(rows) {',
  '  for (const row of rows) {',
  '    if (row.active) {',
  '      while (row.next) {',
  '        if (row.next.valid) {',
  '          const a = row.next.a;',
  '          const b = row.next.b;',
  '          const c = a + b;',
  '        }',
  '      }',
  '    }',
  '  }',
  '}',
].join('\n');

test('genuinely nested control flow is reported, at a 2-space indent', () => {
  const result = scanFiles({ 'messy.js': NESTED_JS });
  assert.equal(rules(result, 'deep-nesting').length, 1);
});

test('nesting is reported in Allman brace style', () => {
  const result = scanFiles({
    'Allman.cs': [
      'public void Build(List<int> rows)',
      '{',
      '    for (var i = 0; i < rows.Count; i++)',
      '    {',
      '        foreach (var r in rows)',
      '        {',
      '            if (r > 0)',
      '            {',
      '                if (r > 1)',
      '                {',
      '                    var a = r;',
      '                    var b = a + r;',
      '                    var c = a + b;',
      '                }',
      '            }',
      '        }',
      '    }',
      '}',
    ].join('\n'),
  });
  assert.equal(rules(result, 'deep-nesting').length, 1);
});

test('callback pyramids count as nesting', () => {
  const result = scanFiles({
    'routes.js': [
      'export function register(app) {',
      "  app.get('/x', async (req, res) => {",
      '    items.forEach((item) => {',
      '      item.parts.forEach((part) => {',
      '        if (part.valid) {',
      '          const a = part.a;',
      '          const b = part.b;',
      '          const c = a + b;',
      '        }',
      '      });',
      '    });',
      '  });',
      '}',
    ].join('\n'),
  });
  assert.equal(rules(result, 'deep-nesting').length, 1);
});

test('JSX element depth is not nesting', () => {
  const result = scanFiles({
    'view.tsx': [
      'export function View({ orders }) {',
      '  return (',
      '    <Layout>',
      '      <Card>',
      '        <div>',
      '          <ul>',
      '            {orders.map((o) => (',
      '              <OrderRow key={o.id} order={o} />',
      '            ))}',
      '          </ul>',
      '        </div>',
      '      </Card>',
      '    </Layout>',
      '  )',
      '}',
    ].join('\n'),
  });
  assert.deepEqual(rules(result, 'deep-nesting'), []);
});

test('object literal depth is not nesting', () => {
  const result = scanFiles({
    'eslint.config.js': [
      'export default {',
      '  rules: {',
      '    complexity: {',
      '      options: {',
      '        thresholds: {',
      '          warn: 11,',
      '          error: 21,',
      '          notes: 31,',
      '        },',
      '      },',
      '    },',
      '  },',
      '}',
    ].join('\n'),
  });
  assert.deepEqual(rules(result, 'deep-nesting'), []);
});

test('nested python control flow is reported, including under except', () => {
  const result = scanFiles({
    'deep.py': [
      'def run(rows):',
      '    for row in rows:',
      '        for cell in row:',
      '            if cell.active:',
      '                try:',
      '                    parse(cell)',
      '                except ValueError:',
      '                    a = cell.a',
      '                    b = cell.b',
      '                    c = a + b',
    ].join('\n'),
  });
  assert.equal(rules(result, 'deep-nesting').length, 1);
});

// --- long-function (issue #6) ---

function jsxComponent(bodyLines) {
  return ['export function Big() {', '  return (', '    <div>', ...bodyLines, '    </div>', '  )', '}'].join('\n');
}

test('a component of mostly markup is not a long function', () => {
  const markup = Array.from({ length: 100 }, (_, i) => `      <Row key={${i}} label="row ${i}" />`);
  const result = scanFiles({ 'orders-view.tsx': jsxComponent(markup) });
  assert.deepEqual(rules(result, 'long-function'), []);
});

test('real logic inside a multi-line element is still a long function', () => {
  const logic = Array.from({ length: 90 }, (_, i) => `        if (v.f${i}) { errors.push(${i}) }`);
  const result = scanFiles({
    'OrderForm.tsx': [
      'export function OrderForm() {',
      '  return (',
      '    <Modal',
      '      title="Order"',
      '      onSubmit={async (values) => {',
      ...logic,
      '      }}',
      '    />',
      '  )',
      '}',
    ].join('\n'),
  });
  assert.equal(rules(result, 'long-function').length, 1, 'a handler with 90 lines of logic must not read as markup');
});

test('a long python function is reported at a 2-space indent', () => {
  const body = Array.from({ length: 90 }, (_, i) => `  v${i} = compute(${i})`);
  const result = scanFiles({ 'long.py': ['def run():', ...body].join('\n') });
  assert.equal(rules(result, 'long-function').length, 1);
});
